### ISSUE TITLE
NameError: global name 'TYPES' is not defined

### ISSUE THREAD

**Issue by syphernl** [robin900/gspread-formatting#1]
I'm trying to set a few cells to the Currency format like this:

```
fmt = CellFormat(numberFormat=NumberFormat(type='CURRENCY'))
```

However, creating a CellFormat results in traceback:
```
  File "PATHNAME/site-packages/gspread_formatting.py", line 327, in __init__
    if type.upper() not in TYPES:
NameError: global name 'TYPES' is not defined

```
I'm running Python 2.7.15rc1 on Ubuntu 18.04.

If I make `TYPES` global, it is working fine.

**Comment by robin900** [comment]
Release 0.0.3 is now in PyPI with a fix, both for NumberFormat.TYPES and Border.STYLES. Sorry about the error!

https://pypi.org/project/gspread-formatting/0.0.3/

Please let me know if the new release works for you...
