### ISSUE TITLE
Support dimension properties (was: Update pixel size)

### ISSUE THREAD

**Issue by vaastav** [robin900/gspread-formatting#10]
Hi, is there a way to update pixel size for the cells?
I can't seem to find a way to do it with your library.

Great work otherwise! Cheers :)

**Comment by robin900** [comment]
I think that TextFormat has a `pixelSize` attribute that does what you want. Let me know if that works for you...

**Comment by vaastav** [comment]
It has fontSize. I want something that changes the size of the cell (increase the width essentially)

**Comment by robin900** [comment]
Then I think you want an updateDimensionProperties request to change the row height. Yes, this operation is currently beyond the scope of my package. Good luck, and if you find a way to offer a pull request to add this feature to the package, I’d be happy to review it!

**Comment by robin900** [comment]
@vaastav I've added `set_row_height` and `set_column_width` support to the package, and released v0.2.0 to include this feature. Let me know if you use it!
