### ISSUE TITLE
Alternating color

### ISSUE THREAD

**Issue by yoonghm** [robin900/gspread-formatting#18]
This is a great piece of work. Thank you.  I am wondering if it is possible to implement alternating colors formatting. Thanks.

**Comment by robin900** [comment]
https://www.bettercloud.com/monitor/the-academy/how-to-automatically-alternate-row-colors-in-google-sheets/

(Summary: You make a conditional formatting rule that uses custom formulas `=ISEVEN(ROW())` and `ISODD(ROW())`.)

**Comment by yoonghm** [comment]
Thanks
