### ISSUE TITLE
InterpolationPoint should have field colorStyle

### ISSUE THREAD

**Issue by branliu0** [robin900/gspread-formatting#23]
**Describe the bug**
The class `InterpolationPoint` should have the field `colorStyle`. See the API documentation: https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/sheets#InterpolationPoint

`get_conditional_format_rules` raises an exception because the API response includes `colorStyle` but the class in this code doesn't know about that field, so it fails with `__init__() got an unexpected keyword argument 'colorStyle'`

**Version and Environment**
*Version of package*: 0.3.1
*Python interpreter*: Python 3.7.8
*OS*: MacOS 10.15

**To Reproduce**
1. Add any conditional formatting rule that includes an InterpolationPoint (e.g., a GradientRule)
2. Save it
3. Read it again with `get_conditional_format_rules`

**Expected behavior**
No exception -- should retrieve the conditional format rules without error.

**Comment by robin900** [comment]
Working on a release to fix this now, @thenovices ...

**Comment by robin900** [comment]
@thenovices Release 0.3.2 contains the fix you requested, and is now in PyPI. Thanks for the reporting the bug!

**Comment by branliu0** [comment]
Wow, what an incredibly fast response time! Thank you so much!
