### ISSUE TITLE
PyCharm and pylint are confused

### ISSUE THREAD

**Issue by belm0** [robin900/gspread-formatting#24]
**Describe the bug**
Neither the PyCharm IDE nor pylint have visibility into members like `gspread_formatting.format_cell_range`

pylint output:
```
E0611: No name 'format_cell_range' in module 'gspread_formatting' (no-name-in-module)
E0611: No name 'set_row_height' in module 'gspread_formatting' (no-name-in-module)
```

**Version and Environment**
*Version of package*: 0.3.2
pylint: 2.6.0
pycharm: 2020.2

**Screenshots**

pycharm:
![Screen Shot 2020-09-24 at 5 11 25 PM](https://user-images.githubusercontent.com/1708631/94119115-695e8c00-fe89-11ea-8f06-539200b3b12e.png)

**Comment by robin900** [comment]
@belm0 I've created PyPI release 0.3.3 of this package, which corrects the problem for PyCharm (and likely other IDEs). I tested the fix with PyCharm 2019.2. The release notes in CHANGELOG.rst explain the cause and the fix.

If you upgrade gspread-formatting to 0.3.3 in your PyCharm project, you should see the red squiggles go away...
