### ISSUE TITLE
Clear Data Validation Rule

### ISSUE THREAD

**Issue by doctorwheauxdat** [robin900/gspread-formatting#26]
So, I ran back over all the issues and dug through the, but was unable to find a way to clear a DataValidationRule from a cell. In order to match the API the method would be to make the  SetDataValidationRequest with no rule specified. I have no recommendation on how to add it to your implementation, but I would find it a useful feature.

[https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#setdatavalidationrequest](url)

**Comment by robin900** [comment]
There's an alternate API way to do this (using `RepeatCellRequest`), but the `gspread_formatting` code wasn't accepting `None` as the parameter to `set_data_validation_rule`. So thanks for reporting your issue! I've made the fix, added to documentation mentioning that a rule parameter of `None` removes any existing data validation rule, and included test coverage. Release 0.3.5 in PyPI will arrive within 20 minutes and include this fix.

**Comment by robin900** [comment]
@doctorwheauxdat Release 0.3.5 is in PyPI now. Enjoy:

```
from gspread_formatting import set_data_validation_rule_for_cell_range

# To clear data validation for cells in range
set_data_validation_rule_for_cell_range(worksheet, cell_range, None)
```
