### ISSUE TITLE
RFE: better support for MultiIndex columns

### ISSUE THREAD

**Issue by sam-s** [robin900/gspread-formatting#28]
**Describe the bug**

Uploading a `DataFrame` with `MultiIndex` columns should merge cells appropriately

**Version and Environment**
*Version of package*: 0.3.7
*Python interpreter*: 
```
Python 3.9.1 (default, Dec 10 2020, 10:36:35) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
```
and `Python 3.6.9` on `Linux 5.4.67`
*OS*: MacOS, Linux

**To Reproduce**
```
df = pd.DataFrame({("a","x"):[1,2,3],("a","y"):[4,5,6],("b","x"):[7,8,9],("b","y"):[1,3,5],"i":[11,11,22],"j":[1,2,2]})
df.set_index(keys=["i","j"],verify_integrity=True, inplace=True)
df.columns = pd.MultiIndex.from_tuples(df.columns)
```
now, `df` is
```
      a     b   
      x  y  x  y
i  j            
11 1  1  4  7  1
   2  2  5  8  3
22 2  3  6  9  5
```
now upload it to google using `set_with_dataframe`.

**Expected behavior**

I expect `a` and `b` to appear on the screen *once*, just like in the printed representation above.

**Screenshots**

here is what I get:

![image](https://user-images.githubusercontent.com/1596894/102299184-85ba1400-3f20-11eb-8d23-6ed02a652b6c.png)

here is what I want:

![image](https://user-images.githubusercontent.com/1596894/102299363-d467ae00-3f20-11eb-8042-50723a9c10d6.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 87

**Comment by sam-s** [comment]
Oops, I forgot that I already asked you about this in https://github.com/robin900/gspread-dataframe/issues/22
Apologies, I guess I need some sleep ;-)

**Comment by robin900** [comment]
Closing this issue, and I've posted the issue's content as a comment to robin900/gspread-dataframe#22
