### ISSUE TITLE
Can't get `get_effective_format()` to work

### ISSUE THREAD

**Issue by uralogical** [robin900/gspread-formatting#34]
Hi, @robin900.

**Describe the bug**
If calling `get_effective_format()` with a cell which is blank both value and formatting, the error below will be happened.

```
Traceback (most recent call last):
  File "doner.py", line 96, in <module>
    is_completed(col)
  File "main.py", line 75, in is_completed
    print(get_effective_format(worksheet, label))
  File "doner.py", line 64, in get_effective_format
    props = resp['sheets'][0]['data'][0]['rowData'][0]['values'][0].get(
KeyError: 'rowData'
```

**Version and Environment**
*Version of package*: 1.0.2
*Python interpreter*: 3.8.0 64bit
*OS*: macOS Big Sur 11.4

**Expected behavior**
Expected to return `None`, but when the cell is blank, the `resp` below returns `{'sheets': [{'data': [{}]}]}`.
It causes the error above.

https://github.com/robin900/gspread-formatting/blob/bdd440fdae4e6f93dbc30b5b765d25105eb96512/gspread_formatting/functions.py#L84-L88

**Comment by robin900** [comment]
@uralogical Thanks for reporting the issue. Fix (with test coverage) about to be committed to master, and package release 1.0.3 will be in PyPI within 10 minutes.

**Comment by robin900** [comment]
@uralogical Release 1.0.3 is now in PyPI. Thanks again for reporting the issue!

**Comment by uralogical** [comment]
@robin900 It worked well! Thanks for rapid fix!
