### ISSUE TITLE
When I try to change the format of the cells, nothing happens.

### ISSUE THREAD

**Issue by ghost** [robin900/gspread-formatting#37]
Good day!
Thank you for your work! I am having problems using the library

I am trying to change the format of cells from text to date, but nothing happens.
Help please, I will be very grateful!

```Python
import os
import gspread
from gspread_formatting import *

gS = gspread.service_account(filename=FILE_GOOGLE_SERVICE)

sH = gS.open(GS_DOCNAME) # gS name
wS_test = sH.worksheet('test')

fmtE = cellFormat(numberFormat=numberFormat(type='DATE'))

p = format_cell_range(wS_test, 'A1:B2', fmtE)
print('\n{}\n'.format(p))

#outpute:
#[{'repeatCell': {'range': {'sheetId': <sheetID>, 'startRowIndex': 0, 'endRowIndex': 2, 'startColumnIndex': 0, 'endColumnIndex': 2}, 'cell': {'userEnteredFormat':  {'numberFormat': {'type': 'DATE'}}}, 'fields': 'userEnteredFormat.numberFormat.type'}}]

```

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/88247104/140776451-4647dd5a-fbf1-4443-96c7-f90830fef3cf.png)

**Version and Environment**
Visual studio code 1.62.0

*Version of package*: 
gspread (4.0.1)
gspread_formatting (1.0.4)

*Python interpreter*:  Python 3.9.7
*OS*:  Windows 10 (build 19041.1288)

**Comment by robin900** [comment]
1. The return value from your `format_cell_range` call does confirm that your call successfully set the `numberFormat` property for the cell range. 
2. It sure looks like your locale's date format is `DD.MM.YYYY`. Are you expecting another date format like `DD/MM/YYYY` instead?
3. Based on the input field in your Sheets screenshot, the value `10.12.2021` in cell B2 is actually using the "text escape apostrophe" at the beginning -- `'10.12.2021` -- which instructs Google Sheets to represent the value as a text literal regardless of the format settings for the cell. If you remove the initial apostrophe from the value in the input field, you should see the format being applied.

Let me know if this cleared up your problem, or if you need further assistance.

**Comment by ghost** [comment]
Thank you very much for your prompt reply!

I recorded Gif
https://drive.google.com/file/d/1n3AlgtHxESlySGVX1iSVmVA7CZbU6fAc/view

1. Yes, I also see what worked right. But the cell format has not changed. (Or I think that it should work like this :) )
2. No, I understand that in order to change the format, you need to use `numberFormat(type='DATE', pattern=##.##.####)`
3. Yes, that's right, my spreadsheet is filled in automatically and Google Sheets recognizes the entered data as a string, and not as a date. But if i change in manual format, it removes the literal. I thought that changing the format through the library does the same.

Thank you!

**Comment by robin900** [comment]
Can you tell me how you are normally writing these cell values to the sheet?

**Comment by ghost** [comment]
I am formating an list of data, it look like this:
``` 
st = list (['07.11.2021', 'Cost', 'Card', 'Food', 'Coffe', 100])
               ^date       ^str    ^str     ^str    ^str    ^float
```
And then using a function to publish the given list to Google Sheets:
```Python
# connect to gS
gS = gspread.service_account(filename=FILE_GOOGLE_SERVICE)
sH = gS.open(GS_DOCNAME) # gS name
wS_Operations = sH.worksheet('Operations')

# date formating function
dt_now = datetime.now().strftime('%d.%m.%Y')

# search for an empty cell for data entry
def searchCellandEntry(col_values, eCell, kCell, n, data=None):
    """1.Get the number of filled cells 
    2.increase by n check if it is empty 
    3.insert data into an empty cell
    ---
    col_values - Column where to check the fullness
    eCell - E colum, the beginning of the border
    kCell - K colum, End of the border
    n - Increasing the row count
    date - Sending data list \ array 
    """
    v_list = wS_Operations.col_values(col_values)
    lenCol_values = len(v_list)
    while True:
        lenCol_values += n
        ValueStr = str(lenCol_values)
        Cell = wS_Operations.acell(eCell + ValueStr).value
        #print('nCell: {} > lenCol_values: {}'.format(eCell, lenCol_values))
        if Cell == None:
            data = [data]
            wS_Operations.update(eCell+ValueStr+':'+kCell+ValueStr, data)
            break
        else:
            wS_Operations.batch_clear([eCell+ValueStr+':'+kCell+ValueStr])
            break
# ---

# start functions 
searchCellandEntry(5, 'E', 'K', 1, st)

```
It looks like this

![image](https://user-images.githubusercontent.com/88247104/140867468-35a780b1-fe86-47a8-a9cd-34f5eb5d17cf.jpeg)

**Comment by robin900** [comment]
OK, so I can confirm that applying a format to a cell via the Sheets web UI does remove the apostrophe escape from a text literal value in that cell. It really surprised me to see that behavior, and of course the Sheets API does not feature that same behavior.

You may want to experiment with the `raw` and `value_input_option` arguments to `update()` and other methods of gspread's `Worksheet` object if you are seeing apostrophe-escaped text literals in your sheets and you didn't want them to be text literals:

https://github.com/burnash/gspread/blob/master/gspread/worksheet.py#L651
