### ISSUE TITLE
gspread-formatting fails to import gspread.models

### ISSUE THREAD

**Issue by vaastav** [robin900/gspread-formatting#38]
**Describe the bug**
gspread-formatting fails to import gspread.models

**Version and Environment**
*Version of package*: Latest version on Pip
*Python interpreter*: Python 3.6+
*OS*: Linux

Error being produced on Github Actions

Here is the traceback:

Traceback (most recent call last):
  File "fixtures.py", line 6, in <module>
    from gspread_formatting import Color, CellFormat, TextFormat, format_cell_ranges, set_frozen
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/gspread_formatting/__init__.py", line 3, in <module>
    from .functions import *
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/gspread_formatting/functions.py", line 12, in <module>
    from gspread.models import Spreadsheet
ModuleNotFoundError: No module named 'gspread.models'

**Comment by robin900** [comment]
@vaastav Thank you for reporting the problem! PyPI now has release 1.0.5 that corrects the problem with gspread 5.0.0.

**Comment by michael-wise** [comment]
Thanks. 

As noted by robin900, make sure that not only gspread is >=5.0.0, but also gspread-formatting is >=1.0.5
(issue was encountered with gspread>5 but gspread-formatting==1.0.3)
