### ISSUE TITLE
Setting width to all columns doesn't work

### ISSUE THREAD

**Issue by livni** [robin900/gspread-formatting#42]
**Describe the bug**
`set_column_widths(sheet, [ ('A:', 100) ])`
Should set all columns to 100 width, but does not change column widths AFAICT

**Version and Environment**
*Version of package*: 1.0.6
*Python interpreter*: Python 3.9.10
*OS*: MacOS

**To Reproduce**
1. Create sheet
2. Change width of column E to larger than the default 100
3. Run `set_column_widths(sheet, [ ('A:', 100) ])`
4. Nothing happens

**Expected behavior**
Column E should have changed width back to 100

**Desktop (please complete the following information):**
 - MacOS 12.3
 - Chrome 101.0.4951.64

**Comment by robin900** [comment]
@livni Thanks for the issue report, and sorry for the delay in responding (was on vacation).

So there's an imprecision in range expressions in "A1 notation", such that you cannot use A1 notation to express every kind of thing you can express with a direct dimension range. The understanding I got from reading the API reference and other materials is that `A:` is shorthand for `A:A`. ~~And `A1:5` is shorthand for `A1:A5`. And `A1:B` is shorthand for `A1:B1`. And so on.~~ If you leave the right side of a range expression completely blank, it is interpreted by gspread-formatting as being a duplication of the left side. Thus `A1:5` means "columns starting with A and unbounded, rows 1 through 5", but `A:` just means `A:A`.

To get the effect you desire, use `A:E` as the range expression, and your width change should work as expected.

**Comment by robin900** [comment]
I'm going to close this issue; feel free to re-open it if you don't find the solution to your issue suitable.

**Comment by livni** [comment]
I guess I'm asking what is the notation for setting the column widths from a certain column onward until the end of the available columns

**Comment by robin900** [comment]
I suppose you could try `A:ZZ` as the range argument for `set_column_width`. Choosing an arbitrarily large value for the "end column" in the range may give you your desired effect.
