### ISSUE TITLE
Formatting a cell whose A1 position I don't know

### ISSUE THREAD

**Issue by ezxpro** [robin900/gspread-formatting#46]
It seems line neither gspread or gspread-formatting allows me to do this. Apparently, formatting is only possible when using the A1 notation.
So,  I'm searching for a value `x` in a cell using gspreads `worksheet.find(x)` method. 
The object returned by is of the type `gspread.cell.Cell`, i.e which [according to the documentation](https://docs.gspread.org/en/v5.6.2/user-guide.html#cell-object) possesses only the attributes "value, row and col". In other words, I can't guess the position of a cell in the A1 notation, so I can't format it either.

**Comment by robin900** [comment]
Look at `gspread.utils.rowcol_to_a1` function in gspread package; pass the row and col values from the cell to that function, and you can proceed with the return value as the A1-notation value...

**Comment by ezxpro** [comment]
@robin900 thank you very much
