### ISSUE TITLE
gspread.exceptions.APIError: {'code': 400

### ISSUE THREAD

**Issue by ghost** [robin900/gspread-formatting#49]
Hello everyone, 
I'm trying to run a Python command for creating Google Sheet report for my test run from Postman and faced the issue 
_gspread.exceptions.APIError: {'code': 400, 'message': "Unable to parse range: 'all prompts'!A1:[5", 'status': 'INVALID_ARGUMENT'}_ 
any ideas on how can I fix it? 
Many thanks

**Comment by robin900** [comment]
It looks like your Python code has a typo `[5` in specifying the cell range: `'all prompts'!A1:[5` instead of maybe `'all prompts'!A1:P5` ?

**Comment by ghost** [comment]
Thank you Robin, 
Unfortunately not, one of my colleague helped today to sort the issue, problem was in limited amount of fields in Python script for the final Google Sheet Report 
Many thanks again

**Comment by robin900** [comment]
No problem, cheers
