### ISSUE TITLE
AttributeError: 'Worksheet' object has no attribute 'spreadsheet'

### ISSUE THREAD

**Issue by simplyshravan** [robin900/gspread-formatting#52]
https://github.com/robin900/gspread-formatting/blob/e895e0eb2bd81fdfbdb4af6618a088adbbc8cd1a/gspread_formatting/dataframe.py#L170

Facing error at above line while using the `gspread_formatting.dataframe.format_with_dataframe` in code. Just curious I am reading a spreadsheet and then creating a worksheet object from the spreadsheet. How in above code we are using worksheet.spreadsheet??

`gc = gspread.authorize(credentials)`
`sht1 = gc.open_by_key(spreadsheet_key)`
`worksheet = sht1.worksheet('Sheet1')`

**Comment by robin900** [comment]
You are using version 6.0.0 of `gspread` which has a bug that removed the `.spreadsheet` attribute from `Worksheet`. Release 6.0.1 fixed the defect; you should upgrade to 6.0.1 or later.

https://github.com/burnash/gspread/releases/tag/v6.0.1
https://github.com/robin900/gspread-formatting/issues/51
