### ISSUE TITLE
Support getting and setting `TextFormatRuns` (was: Does gspread-formatting support changing text colors of a substring in a cell?)

### ISSUE THREAD

**Issue by Amerimac-Github** [robin900/gspread-formatting#54]
I'm looking to build a utility that checks the spelling of one cell against another, and color codes individual words.  Is this possible with gspread-formatting ?  If so, please just mention the feature/method and I can figure it out from the docs (I just don't see it at first pass through the read the docs).  The docs are good I just can't find this capability.  Is it possible or do I need to handroll w the native sheets API?

![image](https://github.com/robin900/gspread-formatting/assets/89217310/054c4956-acdb-4bfe-87c6-a8779278ab31)

**Comment by robin900** [comment]
Sheets API support for "text format runs" is pretty new, and the textFormatRuns array property of CellData didn't exist when gspread-formatting was authored.

This is a good feature to request. I'll make this issue a feature request and work on it should begin fairly soon.

In the meantime, you need a workaround. I recommend exploring the API of Worksheet in the gspread package, and find a way to do a batch update with a RepeatCellRequest for each cell you want to have mixed formatting.  Look in the Sheets API docs for RepeatCellRequest, CellData and TextFormatRun for guidance. Good luck!

**Comment by Amerimac-Github** [comment]
@robin900 thanks, will do.
