### ISSUE TITLE
Using Batch_updater with set_data_validation_for_cell_range

### ISSUE THREAD

**Issue by rmeske** [robin900/gspread-formatting#56]
**Describe the bug**
To avoid the calls per second limitation when setting data validation on many cells, I created a list of cells and rules to update then used batch_updater.  When using set_data_validation_for_cell_range with batch_updater, receive the error:  Worksheet <Worksheet 'Sheet1' id:0> belongs to spreadsheet <Spreadsheet 'Daily_RFQs_Alt' id:id-removed>, not batch updater's spreadsheet <Worksheet 'Sheet1' id:0>

**Version and Environment**
*Version of package*: 1.1.2 
gspread version: 6.1.2
*Python interpreter*: Python 3.10.12
*OS*: Ubuntu 22.04.4 LTS

**To Reproduce**
1. Setup a list of rules.  The variable ws is defined using gspread.  Rows are appended to the worksheet successfully using the variable ws else where in the code.  And if batch_validation.set_data_validation_for_cell_range is called without using batch_updater if will work correctly until it hits the limit.
```
def create_data_validation_rule(row_pos, col_pos, items):
    col_ltr=col_to_letter(col_pos+1)
    cell_address = f"{col_ltr}{row_pos}:{col_ltr}{row_pos}"
    
    rule = DataValidationRule(
        BooleanCondition('ONE_OF_LIST', items),
        showCustomUi=True
    )
    return cell_address, rule
 
 ... code loop to create list of items and position 
 cell_address, rule = create_data_validation_rule(row_pos, col_pos, items) 
rules.append((cell_address, rule))  
```

2. after creating a list of rules then setup the batch
```
      batch_validation = batch_updater(ws)
      for cell_range, rule in rules:
          batch_validation.set_data_validation_for_cell_range(ws,cell_range, rule)
      batch_validation.apply()
```

**Expected behavior**
The batch_updater sends all data validation rules to the api without giving an error that the worksheet does not belong to the updaters spreadsheet.

**Comment by robin900** [comment]
Change `batch_validation = batch_updater(ws)` to ` batch_validation = batch_updater(ws.spreadsheet)`. That should solve your problem.

**Comment by rmeske** [comment]
I made that change and the error is now: 'SpreadsheetBatchUpdater' object has no attribute 'apply'

**Comment by robin900** [comment]
`batch_validation.execute()`

**Comment by rmeske** [comment]
Just realized that and corrected it now I have new error: Invalid requests[78].repeatCell: Range (Sheet1!T102) exceeds grid limits. Max rows: 101, max columns: 38.  Is there a limit on the number of data validations that can be applied in a single batch?

**Comment by robin900** [comment]
You can also use the batch updater in a `with:` block, and it will automatically execute itself at the end of the block:
```
with batch_updater(ws) as batch_validation:
    for cell_range, rule in rules:
        batch_validation.set_data_validation_for_cell_range(ws,cell_range, rule)
```

**Comment by robin900** [comment]
@rmeske `Sheet1!T102` means "Worksheet Sheet1, column T, row 102". The existing worksheet Sheet1 apparently has only 101 rows, so cell `T102` does not exist and thus the error. You may have an off-by-one error in the code that's setting `row_pos`.

**Comment by rmeske** [comment]
Thank you.  It was the row number being off by one in the rules compared to the row data.  
In the with: block, should it be ws.spreadsheet  as well?

**Comment by robin900** [comment]
Yes, `ws.spreadsheet`.

**Comment by rmeske** [comment]
Thank you for your help and this package.
