### ISSUE TITLE
Camel case formatting issue

### ISSUE THREAD

**Issue by Unebrion** [robin900/gspread-formatting#6]
Hi I'm new at this but found your project and it is doing what I need. I am noticing that anything called needs to be in InitialCaps and that camelCase isn't working. At least for me it was telling me I had an unresolved reference. I tested this with CellFormat and Color. 

Thank you very much for making this.

**Comment by robin900** [comment]
Using the latest release (0.0.5) from May 2019:

```
>>> from gspread_formatting import *
>>> CellFormat
<class 'gspread_formatting.CellFormat'>
>>> cellFormat
<class 'gspread_formatting.CellFormat'>
>>> Color
<class 'gspread_formatting.Color'>
>>> color
<class 'gspread_formatting.Color'>
>>>
```

Seems like it's working. Re-open this issue if you continue to have trouble, and provide more info about your package version and the code you're executing that raises the exception.
