### ISSUE TITLE
CellFormat Colour Object 

### ISSUE THREAD

**Issue by dylanlogann** [robin900/gspread-formatting#7]
When formatting a cell with the module, I assume the colour object would be RGB: **color(112, 48, 160)**

However when formatting the cell, its coming back green, which traces back to the RGB of: **rgb(144,208,96)**

Why won't the colours I have entered stick?

**Comment by sknzl** [comment]
I think that 255 corresponds to 1. Therefore (255,255,255) = (1,1,1)
So your color (112,48,160) would be (0.438, 0.187, 0.623). I'm not sure how many digits are considered, and colors could turn out different when converted back to 8bit.

**Comment by robin900** [comment]
@sknzl is correct: the Sheets API wants RGB (and alpha) values to be in the range (0,1); divide each of your typical values by 255.0 and you’ll see the expected results.

There are some illustrative examples at

https://developers.google.com/sheets/api/samples/formatting
