### ISSUE TITLE
Support dataValidation rules (was: Dropdown Selection Cell)

### ISSUE THREAD

**Issue by dylanlogann** [robin900/gspread-formatting#8]
Hi,

I am unable to find any documentation on adding a dropdown selection to a cell, or 'conditional formatting from list'.

Can the module do this?

Cheers.

**Comment by robin900** [comment]
The package currently doesn't support these operations. The conditional formatting features of the Sheets API are rather extensive, but it would be great to see a pull request adding support for them! 😉 

Dropdown selection for cell values seems to require a DataValidationRule -- which the package doesn't currently support but which could be added without too much trouble -- with both the customUi flag set to `true` and the BooleanCondition being of type `ONE_OF_LIST`. This is another pull request opportunity; I don't think I'll be able to add this support myself in the short term...

https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/cells#DataValidationRule  

https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/other#ConditionType

**Comment by robin900** [comment]
@dylanlogann I have a branch which implements data validation rules, including test coverage. Data validation rules will provide the dropdown selection behavior you're looking for, I think. Let me know your thoughts; if this branch will provide the features you need, I'd be happy to put it into a release for tomorrow.

https://github.com/robin900/gspread-formatting/tree/conditional-formatting-8
